### ISSUE TITLE
app.asar recompile for linux

### ISSUE THREAD

**Issue by spidyhackx** [gaganyadav80/bootstrap-crack-linux#1]
Hi buddy, i have the app.asar file for the latest version (5.8.3) ,can you please make it work for linux?

**Comment by gaganyadav80** [comment]
Alright! I will add 5.8.3 in release and also I will commit a bash script that will do all the work and also add a menu entry. With that you could just run the script and launch Bootstrap from your Application menu directly.

**Comment by spidyhackx** [comment]
Ok cool
Thanks buddy <3

**Comment by gaganyadav80** [comment]
Done! Added v5.8.3. 
Simply download the install.sh file and run it using `bash install.sh`.
That's it! No need to do anything else. It will download and add bstudio to your application menu automatically.

**Comment by gaganyadav80** [comment]
Done! Added v5.8.3. 
Simply download the install.sh file and run it using `bash install.sh`.
That's it! No need to do anything else. It will download and add bstudio to your application menu automatically.
